// Centralized Media Asset Store for Royal Fitness Gym Website
// This file serves as the Single Source of Truth for all visual media (Images, Videos, GIFs).
// Updating any URL or path in this file automatically updates the website everywhere without changing component code.

export interface MediaAsset {
  id: string;
  url: string;
  altText: string;
  type: 'image' | 'video' | 'gif' | 'svg';
  aspectRatio: string;
  resolution: string;
  purpose: string;
}

export const MEDIA_ASSETS = {
  hero: {
    background: {
      id: 'hero-bg-01',
      url: 'https://lh3.googleusercontent.com/d/1MwSm6Ie9cMaW9gSZV9C7y68uqvoSYveF',
      fallbackUrl: 'https://drive.google.com/uc?export=view&id=1MwSm6Ie9cMaW9gSZV9C7y68uqvoSYveF',
      altText: 'Royal Fitness Gym Hero Background',
      type: 'image' as const,
      aspectRatio: '16:9 or Fullscreen',
      resolution: '1920x1080 or 4K',
      purpose: 'Main visual backdrop image for the Hero section',
    },
  },

  marquee: {
    gifs: [
      {
        id: 'marquee-gif-01',
        url: 'https://lh3.googleusercontent.com/d/1WW4kYQiy8iIXHNywbOw7Dkxqu2yv9qKs',
        fallbackUrl: 'https://drive.google.com/uc?export=view&id=1WW4kYQiy8iIXHNywbOw7Dkxqu2yv9qKs',
        backupUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80',
        altText: 'Workout loop showcase 1',
        type: 'gif' as const,
        aspectRatio: '16:10',
        resolution: '840x540',
        purpose: '3D Render / Animation loop frame 1',
      },
      {
        id: 'marquee-gif-02',
        url: 'https://lh3.googleusercontent.com/d/1XzYApeZP-cnlMFbmcjt52s-q_nnyQ3Z5',
        fallbackUrl: 'https://drive.google.com/uc?export=view&id=1XzYApeZP-cnlMFbmcjt52s-q_nnyQ3Z5',
        backupUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=800&q=80',
        altText: 'Workout loop showcase 2',
        type: 'gif' as const,
        aspectRatio: '16:10',
        resolution: '840x540',
        purpose: '3D Render / Animation loop frame 2',
      },
      {
        id: 'marquee-gif-03',
        url: 'https://lh3.googleusercontent.com/d/1uKz6xNPX4N5378cfzZx9Dz19uL6ZOGbv',
        fallbackUrl: 'https://drive.google.com/uc?export=view&id=1uKz6xNPX4N5378cfzZx9Dz19uL6ZOGbv',
        backupUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
        altText: 'Workout loop showcase 3',
        type: 'gif' as const,
        aspectRatio: '16:10',
        resolution: '840x540',
        purpose: '3D Render / Animation loop frame 3',
      },
      {
        id: 'marquee-gif-04',
        url: 'https://lh3.googleusercontent.com/d/14nJ2rMxWhoVI3eQzS0NKZAbwLNcs47jF',
        fallbackUrl: 'https://drive.google.com/uc?export=view&id=14nJ2rMxWhoVI3eQzS0NKZAbwLNcs47jF',
        backupUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=80',
        altText: 'Workout loop showcase 4',
        type: 'gif' as const,
        aspectRatio: '16:10',
        resolution: '840x540',
        purpose: '3D Render / Animation loop frame 4',
      },
      {
        id: 'marquee-gif-05',
        url: 'https://lh3.googleusercontent.com/d/1T1ATIpgX-wh-Gn8hSIrLNfSTdcAr6dQ_',
        fallbackUrl: 'https://drive.google.com/uc?export=view&id=1T1ATIpgX-wh-Gn8hSIrLNfSTdcAr6dQ_',
        backupUrl: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=800&q=80',
        altText: 'Workout loop showcase 5',
        type: 'gif' as const,
        aspectRatio: '16:10',
        resolution: '840x540',
        purpose: '3D Render / Animation loop frame 5',
      },
    ],
  },

  projects: [
    {
      number: '01',
      name: 'World-Class Fitness Equipment',
      category: 'Advance Equipment',
      col1Img1: 'https://lh3.googleusercontent.com/d/13VKdO2g3uQAgiU5bm3qTeIjSGO97uR2A',
      col1Img2: 'https://lh3.googleusercontent.com/d/1xowUAcRJSQeB6EZhERvUf7aUaLg8tQ9M',
      col2Img: 'https://lh3.googleusercontent.com/d/1t92_E5LlBXynJ3wTNMiw3dc6_bhCLQoq',
      col1Aspect: 'aspect-video',
    },
    {
      number: '02',
      name: 'Specialised Exercise & Wellness Coaches',
      category: 'Trained Coach',
      col1Img1: 'https://lh3.googleusercontent.com/d/1ro8LD3pluR-tasEize5isKc9CGM9FchT',
      col1Img2: 'https://lh3.googleusercontent.com/d/1pYJHHc8Qm0EPCpbRnAB3Q2i2asuyykbj',
      col2Img: 'https://lh3.googleusercontent.com/d/14MYWuA1W-n6JWsdO8Xga1smh4KyAkO0C',
      col1Aspect: 'aspect-[4/3]',
      col2Aspect: 'aspect-[4/3]',
    },
    {
      number: '03',
      name: 'Our Transformation Champions',
      category: 'The Royal Family',
      col1Img1: 'https://lh3.googleusercontent.com/d/1w7MzMk2bJVqoHqbKuAUBWVwNXzST1pPP',
      col1Img2: 'https://lh3.googleusercontent.com/d/1BjZbgRICIUXM9nFhVXjjfhZ1QjzFXJM0',
      col2Img: 'https://lh3.googleusercontent.com/d/1tt1kAnOX4WASg5zl_EA2-kY7ZYDETfiR',
      col1Aspect: 'aspect-video',
      col2Aspect: 'aspect-[3/4]',
    },
  ],

  menuOverlay: [
    {
      id: 'champion-competition',
      num: '01',
      title: 'Champion Of The Competition',
      subtitle: 'Official Winners across Powerlifting, Strength & Endurance Exercises',
      tag: 'Hall of Fame',
      imgUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'gym-pictures',
      num: '02',
      title: 'Pictures of the Gym',
      subtitle: 'Explore 3D Equipment, Free Weights, Cardio & Content Studio',
      tag: 'Facility Gallery',
      imgUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'member-pictures',
      num: '03',
      title: 'Pictures of Members',
      subtitle: 'Real Transformation Champions, Group Sessions & Spotlights',
      tag: 'Royal Community',
      imgUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'fitness-influencer',
      num: '04',
      title: 'Our Fitness Influencer',
      subtitle: 'Meet Royal Gym Athletes, Creators & Instagram Influencers',
      tag: 'Ambassadors & Creators',
      imgUrl: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'body-fat-calc',
      num: '05',
      title: 'Body Fat Calculator',
      subtitle: 'US Navy Biometric Estimation, Fat Mass & Lean Muscle Analysis',
      tag: 'Biometric Tool',
      imgUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'protein-calc',
      num: '06',
      title: 'Body Weight & Protein Calculator',
      subtitle: 'Daily Protein Target, Calories, Macros & Custom Meal Guides',
      tag: 'Performance Nutrition',
      imgUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'membership-fees',
      num: '07',
      title: 'Memberships Fees & Plans',
      subtitle: 'Day Pass, Monthly Royal Pass, VIP Annual Elite & Coaching Bundles',
      tag: 'Rates & Benefits',
      imgUrl: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=800&q=80',
    },
  ],

  gymFacilityGalleries: [
    {
      id: 1,
      title: 'Heavy Strength & Free Weights Zone',
      category: 'Strength',
      desc: 'Custom Olympic power racks, dumbbells up to 70kg, calibrated steel competition plates, and heavy bench press pods.',
      photos: [
        {
          title: 'Olympic Racks & Power Platforms',
          url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80',
          caption: 'Heavy Duty Olympic Power Racks with Barbell Drop Zones',
        },
        {
          title: 'Dumbbell Section (Up to 70kg)',
          url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=1200&q=80',
          caption: 'Precision Calibrated Dumbbell Racks',
        },
        {
          title: 'Calibrated Competition Steel Plates',
          url: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=1200&q=80',
          caption: 'IPF-Standard Weight Plates & Collars',
        },
        {
          title: 'Heavy Incline & Bench Press Pods',
          url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1200&q=80',
          caption: 'Multi-Angle Commercial Bench Stations',
        },
        {
          title: 'Powerlifting Deadlift Platforms',
          url: 'https://images.unsplash.com/photo-1534367507873-d2d7e24c797f?auto=format&fit=crop&w=1200&q=80',
          caption: 'Shock-Absorbing Rubber Deadlift Platforms',
        },
      ],
    },
    {
      id: 2,
      title: 'High-Tech Cardio & Endurance Floor',
      category: 'Cardio',
      desc: 'Woodway curved treadmills, StairMasters, Concept2 rowers, and Assault bikes with real-time biometric displays.',
      photos: [
        {
          title: 'Woodway Curved Treadmill Row',
          url: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?auto=format&fit=crop&w=1200&q=80',
          caption: 'Self-Powered Motorless Curved Treadmills',
        },
        {
          title: 'StairMaster & Biometric HIIT Floor',
          url: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1200&q=80',
          caption: 'Climber Machines with Heart-Rate Telemetry',
        },
        {
          title: 'Concept2 Rowers & Air Bikes',
          url: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?auto=format&fit=crop&w=1200&q=80',
          caption: 'Aerobic Capacity & Anaerobic Conditioning Station',
        },
        {
          title: 'High-Tech Screen Cardio Suite',
          url: 'https://images.unsplash.com/photo-1576678927484-cc909957088c?auto=format&fit=crop&w=1200&q=80',
          caption: 'Interactive Virtual Course Displays',
        },
        {
          title: 'Endurance Sprint Track View',
          url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1200&q=80',
          caption: 'High-Volume Cardio & Calorie Burn Arena',
        },
      ],
    },
    {
      id: 3,
      title: 'Functional Turf & Agility Track',
      category: 'Functional',
      desc: '30m indoor sled turf track, heavy kettlebells, battle ropes, plyo boxes, and functional agility equipment.',
      photos: [
        {
          title: '30m Indoor Heavy Sled Sprint Track',
          url: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=1200&q=80',
          caption: 'Prowler Sled Push & Pull Turf',
        },
        {
          title: 'Battle Ropes & Kettlebell Racks',
          url: 'https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?auto=format&fit=crop&w=1200&q=80',
          caption: 'Full Cast-Iron Kettlebell Selection (4kg - 48kg)',
        },
        {
          title: 'High-Intensity Turf Zone',
          url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80',
          caption: 'Dynamic Slam Ball & Bodyweight Conditioning',
        },
        {
          title: 'Plyo Box & Agility Ladder Station',
          url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=80',
          caption: 'Explosive Jump & Speed Agility Field',
        },
        {
          title: 'Sled Push & Functional Training Arena',
          url: 'https://images.unsplash.com/photo-1594882645126-14020914d58d?auto=format&fit=crop&w=1200&q=80',
          caption: 'Full-Length Turf Sprint Lane',
        },
      ],
    },
    {
      id: 4,
      title: 'Professional Fitness Content Studio',
      category: 'Studio',
      desc: 'Optimal ring lighting, full-length mirror walls, 4K camera mounts, and cinematic background panels for creators.',
      photos: [
        {
          title: 'Studio Mirror Walls & Ring Lights',
          url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80',
          caption: 'Glare-Free Full Height Mirrors',
        },
        {
          title: 'Creator Lighting & Pose Stage',
          url: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=1200&q=80',
          caption: 'Tunable Color Temperature LED Panels',
        },
        {
          title: 'High-Contrast Aesthetic Backdrops',
          url: 'https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?auto=format&fit=crop&w=1200&q=80',
          caption: 'Royal Gym Custom Neon Posing Backdrop',
        },
        {
          title: 'Cinematic Video Capture Room',
          url: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&w=1200&q=80',
          caption: 'Tripods, Stabilizers & Content Accessories Available',
        },
        {
          title: 'Posing & Social Media Studio Suite',
          url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80',
          caption: 'Private Creator Recording Lounge',
        },
      ],
    },
    {
      id: 5,
      title: 'Royal VIP Coaching & Private Training',
      category: 'VIP',
      desc: 'Exclusive private training pods equipped with personal biometric feedback suites and 1-on-1 certified coaching.',
      photos: [
        {
          title: '1-on-1 Certified Personal Training Pod',
          url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1200&q=80',
          caption: 'Private Pod for Focused 1-on-1 Sessions',
        },
        {
          title: 'Form Analysis & Biometric Assessment',
          url: 'https://images.unsplash.com/photo-1571019614002-c5d8362635a9?auto=format&fit=crop&w=1200&q=80',
          caption: 'Real-Time Motion Capture & Technique Review',
        },
        {
          title: 'Private Elite Power Suite',
          url: 'https://images.unsplash.com/photo-1549060279-7e168fcee0c2?auto=format&fit=crop&w=1200&q=80',
          caption: 'Dedicated VIP Weight Bar & Bench Station',
        },
        {
          title: 'VIP Athletic Performance Coaching',
          url: 'https://images.unsplash.com/photo-1534367507873-d2d7e24c797f?auto=format&fit=crop&w=1200&q=80',
          caption: 'Customized Programming & On-Floor Guidance',
        },
        {
          title: 'Personalised Routine & Power Studio',
          url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80',
          caption: 'Zero Interruption VIP Training Space',
        },
      ],
    },
    {
      id: 6,
      title: 'Hydration Bar & Recovery Sauna Lounge',
      category: 'Recovery',
      desc: 'Purified electrolyte hydration taps, infrared saunas, cold plunge tubs, and complimentary protein shake bar.',
      photos: [
        {
          title: 'Infrared Sauna Suite',
          url: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=1200&q=80',
          caption: 'Deep Tissue Recovery Infrared Sauna (80°C)',
        },
        {
          title: 'Luxury Recovery & Relaxation Lounge',
          url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
          caption: 'Normatec Compression Boots & Reclining Lounge',
        },
        {
          title: 'Electrolyte & Protein Shake Bar',
          url: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=1200&q=80',
          caption: 'Fresh Custom Post-Workout Shakers',
        },
        {
          title: 'Cold Plunge & Hydrotherapy Tubs',
          url: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1200&q=80',
          caption: 'Sub-10°C Ice Baths for Rapid Inflammation Reduction',
        },
        {
          title: 'Fresh Protein Smoothie Station',
          url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1200&q=80',
          caption: 'Complimentary Hydration Taps for Members',
        },
      ],
    },
  ],

  memberMedia: [
    {
      id: 1,
      type: 'video' as const,
      posterTitle: 'OVER POWER',
      subtitle: '2026 MOTION POSTER',
      name: 'Marcus Thorne',
      tag: 'Squat 240kg & Recomp',
      story: 'Heavy compound training twice a week. Built elite power and leg density.',
      mediaUrl: 'https://assets.mixkit.co/videos/preview/mixkit-man-training-with-a-barbell-in-a-gym-42875-large.mp4',
      likes: 482,
      category: 'Video' as const,
    },
    {
      id: 2,
      type: 'video' as const,
      posterTitle: 'UNSTOPPABLE',
      subtitle: 'EXTENDED GRAPHIC',
      name: 'Sarah Jenkins',
      tag: 'Deadlift PR: 165kg',
      story: 'Battle ropes and agility conditioning to build unbreakable stamina.',
      mediaUrl: 'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-crossfit-exercise-with-battle-ropes-42878-large.mp4',
      likes: 619,
      category: 'Video' as const,
    },
    {
      id: 3,
      type: 'image' as const,
      posterTitle: 'THE BEGIN',
      subtitle: '12-WEEK TRANSFORMATION',
      name: 'David K.',
      tag: '-18kg Fat Loss',
      story: 'Trained consistently 4 days/week at Royal Gym with coach nutrition.',
      mediaUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=1200&q=80',
      likes: 389,
      category: 'Transformation' as const,
    },
    {
      id: 4,
      type: 'video' as const,
      posterTitle: 'FOCUS & DRIVE',
      subtitle: 'MOTION REEL',
      name: 'Alex Vance',
      tag: 'Arm Hypertrophy',
      story: 'Isolation & progressive tension in our heavy dumbbell sector.',
      mediaUrl: 'https://assets.mixkit.co/videos/preview/mixkit-athlete-working-out-with-a-dumbbell-in-a-gym-42874-large.mp4',
      likes: 512,
      category: 'Video' as const,
    },
    {
      id: 5,
      type: 'image' as const,
      posterTitle: 'VISIONS',
      subtitle: 'CREATIVE STUDIO',
      name: 'Elena Rostova',
      tag: 'Studio Content Champion',
      story: 'Capturing aesthetic fitness progress under studio-grade ring lights.',
      mediaUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&w=1200&q=80',
      likes: 742,
      category: 'Studio' as const,
    },
    {
      id: 6,
      type: 'video' as const,
      posterTitle: 'LEGENDARY DEPTH',
      subtitle: 'POWER LIFTER',
      name: 'Viktor & Royal Crew',
      tag: 'Barbell Squat Mastery',
      story: 'Strict IPF depth squatting in our private VIP strength pods.',
      mediaUrl: 'https://assets.mixkit.co/videos/preview/mixkit-muscular-man-doing-squats-with-a-barbell-42880-large.mp4',
      likes: 430,
      category: 'Powerlifting' as const,
    },
    {
      id: 7,
      type: 'video' as const,
      posterTitle: 'MOTION DREAMS',
      subtitle: 'HIGH INTENSITY',
      name: 'Jessica Miller',
      tag: 'Sprint Conditioning',
      story: 'High-volume cardio sessions on our Woodway curved treadmills.',
      mediaUrl: 'https://assets.mixkit.co/videos/preview/mixkit-athletic-woman-doing-warm-up-exercises-in-a-gym-42884-large.mp4',
      likes: 395,
      category: 'Video' as const,
    },
    {
      id: 8,
      type: 'image' as const,
      posterTitle: 'TIMELESS',
      subtitle: 'ROYAL COMMUNITY',
      name: '6 AM Morning Squad',
      tag: 'Community Fitness',
      story: 'The early morning team pushing each other through heavy sled pushes.',
      mediaUrl: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=1200&q=80',
      likes: 820,
      category: 'Transformation' as const,
    },
    {
      id: 9,
      type: 'video' as const,
      posterTitle: 'CARDIO ENDURANCE',
      subtitle: 'SLED & SPRINT',
      name: 'Tom & Power Team',
      tag: '30m Turf Sprint',
      story: 'Unstoppable energy on the 30m indoor sled turf track.',
      mediaUrl: 'https://assets.mixkit.co/videos/preview/mixkit-man-runs-on-a-treadmill-in-a-gym-42867-large.mp4',
      likes: 567,
      category: 'Video' as const,
    },
  ],

  influencers: [
    {
      id: 1,
      name: 'Vikram "Titan" Sharma',
      handle: '@vikram_titan_fit',
      category: 'Bodybuilding & Heavy Lifting',
      followers: '485K Followers',
      photoUrl: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?auto=format&fit=crop&w=800&q=80',
      bio: 'IFBB Pro Athlete & Royal Gym Head Strength Ambassador. Specializing in heavy compound mechanics & muscle hypertrophy.',
      igUrl: 'https://www.instagram.com/royalfitness026?igsh=bGZvYmI0MHZnbWhx',
      verified: true,
    },
    {
      id: 2,
      name: 'Aanya Malhotra',
      handle: '@aanya_hybridfit',
      category: 'Functional & Hybrid Fitness',
      followers: '320K Followers',
      photoUrl: 'https://images.unsplash.com/photo-1548690312-e3b507d8c110?auto=format&fit=crop&w=800&q=80',
      bio: 'Hybrid Athlete, Hyrox Competitor & Endurance Coach. Inspiring women to build real power and athletic stamina.',
      igUrl: 'https://www.instagram.com/royalfitness026?igsh=bGZvYmI0MHZnbWhx',
      verified: true,
    },
    {
      id: 3,
      name: 'Rohan Verma',
      handle: '@rohan_power_v',
      category: 'Powerlifting Champion',
      followers: '210K Followers',
      photoUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=800&q=80',
      bio: 'National 83kg Powerlifting Gold Medalist. 310kg Deadlift specialist & biomechanics geek at Royal Gym.',
      igUrl: 'https://www.instagram.com/royalfitness026?igsh=bGZvYmI0MHZnbWhx',
      verified: true,
    },
    {
      id: 4,
      name: 'Priya Nair',
      handle: '@priya_nair_mobility',
      category: 'Calisthenics & Mobility',
      followers: '390K Followers',
      photoUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      bio: 'Bodyweight Mastery & Flexiblity Coach. Teaching handstands, muscle-ups, and injury-free joint mechanics.',
      igUrl: 'https://www.instagram.com/royalfitness026?igsh=bGZvYmI0MHZnbWhx',
      verified: true,
    },
    {
      id: 5,
      name: 'Kabir Mehta',
      handle: '@kabirmehta_shreds',
      category: 'Physique & Nutrition',
      followers: '175K Followers',
      photoUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80',
      bio: 'Men’s Physique Creator & Certified Sports Nutritionist. Transforming elite transformation clients.',
      igUrl: 'https://www.instagram.com/royalfitness026?igsh=bGZvYmI0MHZnbWhx',
      verified: true,
    },
    {
      id: 6,
      name: 'Ananya Deshmukh',
      handle: '@ananya_crossfit_fit',
      category: 'CrossFit & Endurance',
      followers: '290K Followers',
      photoUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=80',
      bio: 'CrossFit Games Regional Competitor & Marathon Runner. Pushing high-intensity mental toughness.',
      igUrl: 'https://www.instagram.com/royalfitness026?igsh=bGZvYmI0MHZnbWhx',
      verified: true,
    },
    {
      id: 7,
      name: 'Devraj Chauhan',
      handle: '@devraj_royal_coach',
      category: 'Royal Master Coach',
      followers: '150K Followers',
      photoUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=800&q=80',
      bio: 'Senior Personal Trainer at Royal Gym. Over 10+ years of body recomposition and athlete sculpting.',
      igUrl: 'https://www.instagram.com/royalfitness026?igsh=bGZvYmI0MHZnbWhx',
      verified: true,
    },
    {
      id: 8,
      name: 'Rhea Roy',
      handle: '@rhea_pilates_fit',
      category: 'Reformer & Core Strength',
      followers: '410K Followers',
      photoUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80',
      bio: 'Reformer Pilates Master & Core Sculpting Influencer. Empowering posture and deep abdominal power.',
      igUrl: 'https://www.instagram.com/royalfitness026?igsh=bGZvYmI0MHZnbWhx',
      verified: true,
    },
    {
      id: 9,
      name: 'Siddharth "Sid" Malhotra',
      handle: '@sid_aesthetic_fit',
      category: 'Natural Aesthetics & Vlogs',
      followers: '530K Followers',
      photoUrl: 'https://images.unsplash.com/photo-1507398941214-572c25f4b1dc?auto=format&fit=crop&w=800&q=80',
      bio: 'Fitness Vlogger & Natural Aesthetics Advocate. Motivating millions daily through fitness content creation.',
      igUrl: 'https://www.instagram.com/royalfitness026?igsh=bGZvYmI0MHZnbWhx',
      verified: true,
    },
  ],

  collabVideos: [
    {
      id: 1,
      title: 'Titan x Rohan: 300KG Heavy Deadlift & Squat Battle',
      influencerName: 'Vikram Titan & Rohan Verma',
      influencerHandle: '@vikram_titan_fit x @rohan_power_v',
      influencerPhoto: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?auto=format&fit=crop&w=800&q=80',
      videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-muscular-man-doing-squats-with-a-barbell-42880-large.mp4',
      posterUrl: 'https://images.unsplash.com/photo-1534367507873-d2d7e24c797f?auto=format&fit=crop&w=800&q=80',
      duration: '0:48',
      views: '124K Views',
      likes: '18.4K',
      category: 'Powerlifting Collab',
      description: 'Official Royal Gym powerlifting showdown testing max squat and deadlift singles on our calibrated competition platforms.',
      igUrl: 'https://www.instagram.com/royalfitness026?igsh=bGZvYmI0MHZnbWhx',
    },
    {
      id: 2,
      title: 'Aanya x Priya: Hybrid Conditioning & Mobility Mastery',
      influencerName: 'Aanya Malhotra & Priya Nair',
      influencerHandle: '@aanya_hybridfit x @priya_nair_mobility',
      influencerPhoto: 'https://images.unsplash.com/photo-1548690312-e3b507d8c110?auto=format&fit=crop&w=800&q=80',
      videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-athletic-woman-doing-warm-up-exercises-in-a-gym-42884-large.mp4',
      posterUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
      duration: '0:52',
      views: '98K Views',
      likes: '14.2K',
      category: 'Mobility & HIIT',
      description: 'Combining functional stamina with joint mobility drills in our turf area. Learn mobility routines before heavy lifts.',
      igUrl: 'https://www.instagram.com/royalfitness026?igsh=bGZvYmI0MHZnbWhx',
    },
    {
      id: 3,
      title: 'Kabir x Sid: Aesthetic Posing & 3D Studio Vlog',
      influencerName: 'Kabir Mehta & Sid Malhotra',
      influencerHandle: '@kabirmehta_shreds x @sid_aesthetic_fit',
      influencerPhoto: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80',
      videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-athlete-working-out-with-a-dumbbell-in-a-gym-42874-large.mp4',
      posterUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&w=800&q=80',
      duration: '1:15',
      views: '210K Views',
      likes: '31.5K',
      category: 'Studio Posing Reel',
      description: 'Behind the scenes at Royal Gym Content Studio using ring lights and neon backdrops for competition conditioning clips.',
      igUrl: 'https://www.instagram.com/royalfitness026?igsh=bGZvYmI0MHZnbWhx',
    },
    {
      id: 4,
      title: 'Devraj x Ananya: 30m Sled Push & Sprint Battle',
      influencerName: 'Devraj Chauhan & Ananya Deshmukh',
      influencerHandle: '@devraj_royal_coach x @ananya_crossfit_fit',
      influencerPhoto: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=800&q=80',
      videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-man-runs-on-a-treadmill-in-a-gym-42867-large.mp4',
      posterUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=80',
      duration: '0:40',
      views: '85K Views',
      likes: '11.8K',
      category: 'CrossFit Sprint',
      description: 'High-octane sprint conditioning and heavy sled pushes on our indoor turf lane. Pure speed and power.',
      igUrl: 'https://www.instagram.com/royalfitness026?igsh=bGZvYmI0MHZnbWhx',
    },
    {
      id: 5,
      title: 'Rhea x Aanya: Reformer Core & Full-Body Burn',
      influencerName: 'Rhea Roy & Aanya Malhotra',
      influencerHandle: '@rhea_pilates_fit x @aanya_hybridfit',
      influencerPhoto: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80',
      videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-woman-doing-crossfit-exercises-in-a-gym-42885-large.mp4',
      posterUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80',
      duration: '0:55',
      views: '115K Views',
      likes: '16.9K',
      category: 'Pilates Collab',
      description: 'Strengthening stabilizer muscles and deep core control in our dedicated reformer and functional recovery lounge.',
      igUrl: 'https://www.instagram.com/royalfitness026?igsh=bGZvYmI0MHZnbWhx',
    },
    {
      id: 6,
      title: 'Royal Creator Summit: All-Star Ambassador Workout',
      influencerName: 'Royal Gym Creator Squad',
      influencerHandle: '@royalfitness026 Ambassadors',
      influencerPhoto: 'https://images.unsplash.com/photo-1507398941214-572c25f4b1dc?auto=format&fit=crop&w=800&q=80',
      videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-man-doing-crossfit-exercises-with-a-barbell-42882-large.mp4',
      posterUrl: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=800&q=80',
      duration: '1:30',
      views: '340K Views',
      likes: '48.2K',
      category: 'Community Reel',
      description: 'Highlights from our annual Royal Fitness Ambassador Meetup featuring all 9 creators in action across gym zones.',
      igUrl: 'https://www.instagram.com/royalfitness026?igsh=bGZvYmI0MHZnbWhx',
    },
  ],

  competitionChampions: [
    {
      id: 1,
      exerciseName: 'Barbell Deadlift',
      personName: 'Vikram "Titan" Sharma',
      photoUrl: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 2,
      exerciseName: 'Barbell Bench Press',
      personName: 'Marcus Thorne',
      photoUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 3,
      exerciseName: 'Barbell Squat',
      personName: 'Rohan Verma',
      photoUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 4,
      exerciseName: 'Weighted Pull-Ups',
      personName: 'Priya Nair',
      photoUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 5,
      exerciseName: 'Plank Endurance Hold',
      personName: 'Aanya Malhotra',
      photoUrl: 'https://images.unsplash.com/photo-1548690312-e3b507d8c110?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 6,
      exerciseName: 'Overhead Dumbbell Press',
      personName: 'Kabir Mehta',
      photoUrl: 'https://images.unsplash.com/photo-1507398941214-572c25f4b1dc?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 7,
      exerciseName: '30m Sled Push Sprint',
      personName: 'Ananya Deshmukh',
      photoUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 8,
      exerciseName: 'Strict Bicep Curls',
      personName: 'Sid Malhotra',
      photoUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 9,
      exerciseName: 'Reformer Core Hold',
      personName: 'Rhea Roy',
      photoUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80',
    },
  ],
};
